name: Webhook Workflow

on: #the triggers, for more info, visit https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#workflow_run
  push:
  pull_request: 

jobs:
  trigger_webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Webhook Send
        uses: krungkualalumpur/discord-webhook-action@v3
        with: 
          url: ${{ secrets.KARYA_WEBHOOK_URL }}